# Generated by Django 4.1.1 on 2022-09-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beZen_app', '0002_alter_note_created_alter_note_lastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
